# This file is distributed under the same license as the Django package.
#
# Translators:
# Jannis Leidel <jannis@leidel.info>, 2011
# Masashi SHIBATA <contact@c-bata.link>, 2017
# Shinya Okano <tokibito@gmail.com>, 2013-2016
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-02-10 12:30-0200\n"
"PO-Revision-Date: 2017-09-24 17:59+0000\n"
"Last-Translator: Masashi SHIBATA <contact@c-bata.link>\n"
"Language-Team: Japanese (http://www.transifex.com/django/django/language/"
"ja/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: .\myvenv\Lib\site-packages\django\contrib\auth\admin.py:46
msgid "Personal info"
msgstr "個人情報"

#: .\myvenv\Lib\site-packages\django\contrib\auth\admin.py:47
msgid "Permissions"
msgstr "パーミッション"

#: .\myvenv\Lib\site-packages\django\contrib\auth\admin.py:49
msgid "Important dates"
msgstr "重要な日程"

#: .\myvenv\Lib\site-packages\django\contrib\auth\admin.py:135
#, python-format
msgid "%(name)s object with primary key %(key)r does not exist."
msgstr "主キーが %(key)r である %(name)s オブジェクトは存在しません。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\admin.py:145
msgid "Password changed successfully."
msgstr "パスワードを変更しました"

#: .\myvenv\Lib\site-packages\django\contrib\auth\admin.py:165
#, python-format
msgid "Change password: %s"
msgstr "パスワードの変更: %s"

#: .\myvenv\Lib\site-packages\django\contrib\auth\apps.py:14
msgid "Authentication and Authorization"
msgstr "認証と認可"

#: .\myvenv\Lib\site-packages\django\contrib\auth\base_user.py:48
msgid "password"
msgstr "パスワード"

#: .\myvenv\Lib\site-packages\django\contrib\auth\base_user.py:49
msgid "last login"
msgstr "最終ログイン"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:30
msgid "No password set."
msgstr "パスワードは設定されませんでした。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:35
msgid "Invalid password format or unknown hashing algorithm."
msgstr "無効なパスワードか不明なハッシュアルゴリズムです。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:70
#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:307
#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:379
msgid "The two password fields didn't match."
msgstr "確認用パスワードが一致しません。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:73
#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:126
#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:163
#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:383
msgid "Password"
msgstr "パスワード"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:79
msgid "Password confirmation"
msgstr "パスワードの確認"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:82
#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:392
msgid "Enter the same password as before, for verification."
msgstr "確認のため、再度パスワードを入力してください。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:128
msgid ""
"Raw passwords are not stored, so there is no way to see this user's "
"password, but you can change the password using <a href=\"{}\">this form</a>."
msgstr ""
"生のパスワードは格納されていないため、このユーザのパスワードを確認する方法は"
"ありません。しかし<a href=\"{}\">このフォーム</a>をしようして　パスワードを変"
"更できます。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:170
#, python-format
msgid ""
"Please enter a correct %(username)s and password. Note that both fields may "
"be case-sensitive."
msgstr ""
"正しい%(username)sとパスワードを入力してください。どちらのフィールドも大文字"
"と小文字は区別されます。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:173
msgid "This account is inactive."
msgstr "アカウントが無効です。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:234
msgid "Email"
msgstr "メールアドレス"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:310
msgid "New password"
msgstr "新しいパスワード"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:316
msgid "New password confirmation"
msgstr "新しいパスワード(確認用)"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:351
msgid "Your old password was entered incorrectly. Please enter it again."
msgstr "元のパスワードが間違っています。もう一度入力してください。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:354
msgid "Old password"
msgstr "元のパスワード"

#: .\myvenv\Lib\site-packages\django\contrib\auth\forms.py:389
msgid "Password (again)"
msgstr "パスワード(確認用)"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:263
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:337
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:434
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:496
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:527
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:563
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:599
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:637
msgid "algorithm"
msgstr "アルゴリズム"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:264
msgid "iterations"
msgstr "イテレーション"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:265
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:343
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:436
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:497
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:528
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:638
msgid "salt"
msgstr "ソルト"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:266
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:344
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:498
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:529
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:564
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:600
#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:639
msgid "hash"
msgstr "ハッシュ"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:338
msgid "variety"
msgstr "多様性"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:339
msgid "version"
msgstr "バージョン"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:340
msgid "memory cost"
msgstr "メモリーコスト"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:341
msgid "time cost"
msgstr "時間コスト"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:342
msgid "parallelism"
msgstr "並行性"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:435
msgid "work factor"
msgstr "ワークファクター"

#: .\myvenv\Lib\site-packages\django\contrib\auth\hashers.py:437
msgid "checksum"
msgstr "チェックサム"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:56
#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:111
msgid "name"
msgstr "名前"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:60
msgid "content type"
msgstr "コンテンツタイプ"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:62
msgid "codename"
msgstr "コード名"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:66
msgid "permission"
msgstr "パーミッション"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:67
#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:114
msgid "permissions"
msgstr "パーミッション"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:121
msgid "group"
msgstr "グループ"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:122
#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:218
msgid "groups"
msgstr "グループ"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:209
msgid "superuser status"
msgstr "スーパーユーザー権限"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:212
msgid ""
"Designates that this user has all permissions without explicitly assigning "
"them."
msgstr "全ての権限を持っているとみなされます。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:221
msgid ""
"The groups this user belongs to. A user will get all permissions granted to "
"each of their groups."
msgstr ""
"このユーザーが所属するグループ。ユーザーはそれぞれのグループに付与されたすべ"
"ての権限を持ちます。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:229
msgid "user permissions"
msgstr "ユーザーパーミッション"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:231
msgid "Specific permissions for this user."
msgstr "このユーザーの持つ権限です。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:298
msgid "username"
msgstr "ユーザー名"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:301
msgid "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
msgstr ""
"この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にし"
"てください。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:304
msgid "A user with that username already exists."
msgstr "同じユーザー名が既に登録済みです。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:307
msgid "first name"
msgstr "名"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:308
msgid "last name"
msgstr "姓"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:309
msgid "email address"
msgstr "メールアドレス"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:311
msgid "staff status"
msgstr "スタッフ権限"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:313
msgid "Designates whether the user can log into this admin site."
msgstr "ユーザーが管理サイトにログイン可能かどうかを示します。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:316
msgid "active"
msgstr "有効"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:319
msgid ""
"Designates whether this user should be treated as active. Unselect this "
"instead of deleting accounts."
msgstr ""
"ユーザーがアクティブかどうかを示します。アカウントを消す代わりに選択を解除し"
"てください。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:323
msgid "date joined"
msgstr "登録日"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:332
msgid "user"
msgstr "ユーザー"

#: .\myvenv\Lib\site-packages\django\contrib\auth\models.py:333
msgid "users"
msgstr "ユーザー"

#: .\myvenv\Lib\site-packages\django\contrib\auth\password_validation.py:102
#, python-format
msgid ""
"This password is too short. It must contain at least %(min_length)d "
"character."
msgid_plural ""
"This password is too short. It must contain at least %(min_length)d "
"characters."
msgstr[0] "このパスワードは短すぎます。最低 %(min_length)d 文字以上必要です。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\password_validation.py:112
#, python-format
msgid "Your password must contain at least %(min_length)d character."
msgid_plural "Your password must contain at least %(min_length)d characters."
msgstr[0] "パスワードは最低 %(min_length)d 文字以上必要です。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\password_validation.py:151
#, python-format
msgid "The password is too similar to the %(verbose_name)s."
msgstr "このパスワードは %(verbose_name)s と似すぎています。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\password_validation.py:157
msgid "Your password can't be too similar to your other personal information."
msgstr "あなたの他の個人情報と似ているパスワードにはできません。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\password_validation.py:185
msgid "This password is too common."
msgstr "このパスワードは一般的すぎます。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\password_validation.py:190
msgid "Your password can't be a commonly used password."
msgstr "よく使われるパスワードにはできません。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\password_validation.py:200
msgid "This password is entirely numeric."
msgstr "このパスワードは数字しか使われていません。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\password_validation.py:205
msgid "Your password can't be entirely numeric."
msgstr "数字だけのパスワードにはできません。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\templates\registration\password_reset_subject.txt:2
#, python-format
msgid "Password reset on %(site_name)s"
msgstr "%(site_name)s のパスワードリセット"

#: .\myvenv\Lib\site-packages\django\contrib\auth\validators.py:12
msgid ""
"Enter a valid username. This value may contain only English letters, "
"numbers, and @/./+/-/_ characters."
msgstr ""
"有効なユーザー名を入力してください。半角英数、 @/./+/-/_ を使用できます。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\validators.py:22
msgid ""
"Enter a valid username. This value may contain only letters, numbers, and "
"@/./+/-/_ characters."
msgstr ""
"有効なユーザー名を入力してください。半角英数、 @/./+/-/_ を使用できます。"

#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:181
msgid "Logged out"
msgstr "ログアウト"

#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:283
#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:402
msgid "Password reset"
msgstr "パスワードをリセット"

#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:298
#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:430
msgid "Password reset sent"
msgstr "パスワードリセットを送信しました"

#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:336
#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:439
msgid "Enter new password"
msgstr "新しいパスワードを入力してください"

#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:347
#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:499
msgid "Password reset unsuccessful"
msgstr "パスワードのリセットに失敗しました"

#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:367
#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:507
msgid "Password reset complete"
msgstr "パスワードがリセットされました"

#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:542
#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:570
msgid "Password change"
msgstr "パスワードの変更"

#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:558
#: .\myvenv\Lib\site-packages\django\contrib\auth\views.py:593
msgid "Password change successful"
msgstr "パスワードを変更しました"
